add pimlico gas price query
fun-xyz/funkit-core pull request #370
Opened 2023-09-18 22:56 UTC by Chazzzzzzz

2023-09-18 23:32 UTC, Chazzzzzzz commented
<img width="747" alt="image" src="https://github.com/fun-xyz/funkit-core/assets/42802149/00f4b465-8831-4eca-b4dc-c32ef965477f">

2023-09-18 23:34 UTC, Chazzzzzzz commented
<img width="696" alt="image" src="https://github.com/fun-xyz/funkit-core/assets/42802149/b63df9c5-2f0c-492e-afc8-edc282d8305d">

2023-09-18 23:45 UTC, Chazzzzzzz commented
<img width="809" alt="image" src="https://github.com/fun-xyz/funkit-core/assets/42802149/01ec2ef2-a175-4c99-aa46-ee1172d80bf1">

2023-09-18 23:47 UTC, Chazzzzzzz commented
<img width="732" alt="image" src="https://github.com/fun-xyz/funkit-core/assets/42802149/60b49458-a8c1-463a-8815-87458496cb3f">

2023-09-18 23:59 UTC, AlbertSu123 requested changes

2023-09-18 23:59 UTC, AlbertSu123 commented on src/apis/types.ts
> +export type GasPrice = {
Rename this to UserOperationGasPrice instead of gas price since this is userOperationGas specific

2023-09-18 23:59 UTC, AlbertSu123 commented on src/wallet/FunWallet.ts
> +        var maxFeePerGas, maxPriorityFeePerGas
why var instead of let?

2023-09-19 00:09 UTC, Chazzzzzzz commented on src/apis/types.ts
> +export type GasPrice = {
make sense!

2023-09-19 00:19 UTC, Chazzzzzzz commented
test pass after resolving comments

<img width="710" alt="image" src="https://github.com/fun-xyz/funkit-core/assets/42802149/0d72060b-5884-4dfc-b647-3f099064787d">

2023-09-19 00:25 UTC, AlbertSu123 approved these changes

2023-09-19 00:26 UTC, merged